{
  try {
    this.destroy();
  }
 catch (  Throwable ex) {
    log.error(ex);
  }
}
